# Generated by Django 4.2.23 on 2025-06-12 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='DT_CRIADO_EM', verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='DT_ATUALIZADO_EM', verbose_name='Atualizado em')),
                ('id', models.AutoField(db_column='PK_PAIS', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NO_PAIS', max_length=255)),
                ('nome_esp', models.CharField(db_column='NO_PAIS_ESP', max_length=255)),
                ('nome_eng', models.CharField(db_column='NO_PAIS_ENG', max_length=255)),
                ('sigla', models.CharField(db_column='CO_SIGLA', max_length=2)),
            ],
            options={
                'verbose_name': 'País',
                'db_table': 'TB_PAIS',
            },
        ),
        migrations.CreateModel(
            name='TipoEndereco',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='DT_CRIADO_EM', verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='DT_ATUALIZADO_EM', verbose_name='Atualizado em')),
                ('id', models.AutoField(db_column='PK_TIPO_ENDERECO', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NO_TIPO_ENDERECO', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Tipos de Endereço',
                'db_table': 'TB_TIPO_ENDERECO',
            },
        ),
        migrations.CreateModel(
            name='UnidadeFederativa',
            fields=[
                ('id', models.AutoField(db_column='PK_UNIDADE_FEDERATIVA', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NO_UF', max_length=19)),
                ('sigla', models.CharField(db_column='SG_UF', max_length=2)),
            ],
            options={
                'verbose_name': 'Unidade Federativa',
                'verbose_name_plural': 'Unidades Federativas',
                'db_table': 'TB_UNIDADE_FEDERATIVA',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(db_column='PK_MUNICIPIO', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NO_MUNICIPIO', max_length=50)),
                ('cnpj', models.CharField(blank=True, db_column='NU_CNPJ', max_length=18, null=True)),
                ('cod_ibge', models.PositiveIntegerField(db_column='CO_IBGE', unique=True)),
                ('lat', models.DecimalField(blank=True, db_column='CG_LATITUDE', decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('lon', models.DecimalField(blank=True, db_column='CG_LONGITUDE', decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('uf', models.ForeignKey(db_column='FK_UF', on_delete=django.db.models.deletion.PROTECT, to='enderecos.unidadefederativa', verbose_name='Unidade Federativa')),
            ],
            options={
                'verbose_name': 'Município',
                'db_table': 'TB_MUNICIPIO',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='DT_CRIADO_EM', verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='DT_ATUALIZADO_EM', verbose_name='Atualizado em')),
                ('id', models.AutoField(db_column='PK_ENDERECO', primary_key=True, serialize=False)),
                ('rua', models.CharField(blank=True, db_column='NO_RUA', max_length=250, null=True)),
                ('numero', models.CharField(blank=True, db_column='NU_NUMERO', max_length=8, null=True)),
                ('complemento', models.CharField(blank=True, db_column='NO_COMPLEMENTO', max_length=120, null=True)),
                ('bairro', models.CharField(blank=True, db_column='NO_BAIRRO', max_length=120, null=True)),
                ('cep', models.CharField(blank=True, db_column='CO_CEP', max_length=8, null=True, verbose_name='CEP')),
                ('lat', models.DecimalField(blank=True, db_column='CG_LATITUDE', decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('lon', models.DecimalField(blank=True, db_column='CG_LONGITUDE', decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('municipio', models.ForeignKey(db_column='FK_MUNICIPIO', on_delete=django.db.models.deletion.PROTECT, related_name='enderecos', to='enderecos.municipio', verbose_name='Município')),
                ('tipo_endereco', models.ForeignKey(db_column='FK_TIPO_ENDERECO', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='enderecos', to='enderecos.tipoendereco', verbose_name='Tipos de Endereço')),
            ],
            options={
                'verbose_name': 'Endereço',
                'db_table': 'TB_ENDERECO',
            },
        ),
    ]
