# Generated by Django 4.2.23 on 2025-06-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipio',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='cod_ibge',
        ),
    ]
