# Generated by Django 4.2.23 on 2025-06-12 13:09

from django.db import migrations

def adicionar_tipos_endereco(apps, schema_editor):
    TipoEndereco = apps.get_model('enderecos', 'TipoEndereco')

    TipoEndereco.objects.update_or_create(
        nome='Residencial'
    )

    TipoEndereco.objects.update_or_create(
        nome='Comercial'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0003_auto_20250612_1223'),
    ]

    operations = [
        migrations.RunPython(adicionar_tipos_endereco),
    ]
