# Generated by Django 4.2.23 on 2025-06-12 02:42

import apps.autenticacao.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contatos', '0001_initial'),
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(db_column='CO_USUARIO', max_length=35, unique=True, verbose_name='CPF')),
                ('is_active', models.BooleanField(db_column='ST_ATIVO', default=True)),
                ('is_superuser', models.BooleanField(db_column='ST_SUPER', default=False)),
                ('is_staff', models.BooleanField(db_column='ST_ADMIN', default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário base',
                'verbose_name_plural': 'Usuários base',
                'db_table': 'TB_USUARIO_BASE',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='DT_CRIADO_EM', verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='DT_ATUALIZADO_EM', verbose_name='Atualizado em')),
                ('id', models.AutoField(db_column='PK_GRUPO', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NO_GRUPO', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'TB_GRUPO',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='DT_CRIADO_EM', verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='DT_ATUALIZADO_EM', verbose_name='Atualizado em')),
                ('id', models.AutoField(db_column='PK_MODULO', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NO_MODULO', max_length=255, unique=True)),
                ('descricao', models.TextField(db_column='DS_MODULO')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'db_table': 'TB_MODULO',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='DT_CRIADO_EM', verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='DT_ATUALIZADO_EM', verbose_name='Atualizado em')),
                ('id', models.AutoField(db_column='PK_USUARIO', primary_key=True, serialize=False)),
                ('cpf', models.CharField(db_column='CO_CPF', max_length=11, unique=True)),
                ('nome', models.CharField(db_column='NO_NOME_COMPLETO', max_length=255)),
                ('nome_social', models.CharField(blank=True, db_column='NO_NOME_SOCIAL', max_length=255, null=True)),
                ('profissao', models.CharField(blank=True, db_column='NO_PROFISSAO', max_length=255, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], db_column='CO_SEXO', max_length=1, null=True)),
                ('data_nascimento', models.DateField(db_column='DT_NASCIMENTO', null=True)),
                ('telefone', models.CharField(blank=True, db_column='NO_TELEFONE', max_length=15, null=True)),
                ('email', models.EmailField(db_column='NO_EMAIL', max_length=254)),
                ('status', models.BooleanField(db_column='NO_STATUS', default=False)),
                ('foto', models.FileField(blank=True, db_column='NO_FOTO', max_length=200, null=True, upload_to=apps.autenticacao.models.imagem_perfil_path, validators=[apps.autenticacao.models.validate_file_extension])),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'TB_USUARIO',
            },
        ),
        migrations.CreateModel(
            name='UsuarioEndereco',
            fields=[
                ('id', models.AutoField(db_column='PK_USUARIO_ENDERECO', primary_key=True, serialize=False)),
                ('endereco', models.ForeignKey(db_column='FK_ENDERECO', on_delete=django.db.models.deletion.CASCADE, to='enderecos.endereco')),
                ('usuario', models.ForeignKey(db_column='FK_USUARIO', on_delete=django.db.models.deletion.CASCADE, to='autenticacao.usuario')),
            ],
            options={
                'db_table': 'TB_USUARIO_ENDERECO',
            },
        ),
        migrations.CreateModel(
            name='UsuarioContato',
            fields=[
                ('id', models.AutoField(db_column='PK_USUARIO_CONTATO', primary_key=True, serialize=False)),
                ('contato', models.ForeignKey(db_column='FK_CONTATO', on_delete=django.db.models.deletion.CASCADE, to='contatos.contato')),
                ('usuario', models.ForeignKey(db_column='FK_USUARIO', on_delete=django.db.models.deletion.CASCADE, to='autenticacao.usuario')),
            ],
            options={
                'db_table': 'TB_USUARIO_CONTATO',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='contatos',
            field=models.ManyToManyField(related_name='usuario_contatos', through='autenticacao.UsuarioContato', to='contatos.contato'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='enderecos',
            field=models.ManyToManyField(related_name='usuario_enderecos', through='autenticacao.UsuarioEndereco', to='enderecos.endereco'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pais_origem',
            field=models.ForeignKey(blank=True, db_column='FK_PAIS_ORIGEM', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_gestao', to='enderecos.pais', verbose_name='País de Origem'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(db_column='CO_USER', on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='DT_CRIADO_EM', verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='DT_ATUALIZADO_EM', verbose_name='Atualizado em')),
                ('id', models.AutoField(db_column='PK_PERMISSAO', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NO_PERMISSAO', max_length=255, unique=True)),
                ('descricao', models.TextField(db_column='DS_PERMISSAO')),
                ('modulo', models.ForeignKey(db_column='FK_MODULO', on_delete=django.db.models.deletion.PROTECT, to='autenticacao.modulo')),
            ],
            options={
                'verbose_name': 'Permissao',
                'verbose_name_plural': 'Permissões',
                'db_table': 'TB_PERMISSAO',
            },
        ),
        migrations.CreateModel(
            name='HistoricalUsuario',
            fields=[
                ('criado_em', models.DateTimeField(blank=True, db_column='DT_CRIADO_EM', editable=False, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(blank=True, db_column='DT_ATUALIZADO_EM', editable=False, verbose_name='Atualizado em')),
                ('id', models.IntegerField(blank=True, db_column='PK_USUARIO', db_index=True)),
                ('cpf', models.CharField(db_column='CO_CPF', db_index=True, max_length=11)),
                ('nome', models.CharField(db_column='NO_NOME_COMPLETO', max_length=255)),
                ('nome_social', models.CharField(blank=True, db_column='NO_NOME_SOCIAL', max_length=255, null=True)),
                ('profissao', models.CharField(blank=True, db_column='NO_PROFISSAO', max_length=255, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], db_column='CO_SEXO', max_length=1, null=True)),
                ('data_nascimento', models.DateField(db_column='DT_NASCIMENTO', null=True)),
                ('telefone', models.CharField(blank=True, db_column='NO_TELEFONE', max_length=15, null=True)),
                ('email', models.EmailField(db_column='NO_EMAIL', max_length=254)),
                ('status', models.BooleanField(db_column='NO_STATUS', default=False)),
                ('foto', models.TextField(blank=True, db_column='NO_FOTO', max_length=200, null=True, validators=[apps.autenticacao.models.validate_file_extension])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='historico_usuario', to='autenticacao.usuario')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pais_origem', models.ForeignKey(blank=True, db_column='FK_PAIS_ORIGEM', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='enderecos.pais', verbose_name='País de Origem')),
                ('user', models.ForeignKey(blank=True, db_column='CO_USER', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Usuário',
                'verbose_name_plural': 'historical Usuários',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='GrupoPermissao',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='DT_CRIADO_EM', verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='DT_ATUALIZADO_EM', verbose_name='Atualizado em')),
                ('id', models.AutoField(db_column='PK_GRUPO_PERMISSAO', primary_key=True, serialize=False)),
                ('grupo', models.ForeignKey(db_column='FK_GRUPO', on_delete=django.db.models.deletion.PROTECT, to='autenticacao.grupo')),
                ('permissao', models.ForeignKey(db_column='FK_PERMISSAO', on_delete=django.db.models.deletion.PROTECT, to='autenticacao.permissao')),
            ],
            options={
                'verbose_name': 'Relação Entre Grupo e Permissão',
                'verbose_name_plural': 'Relação entre Grupos e Permissões',
                'db_table': 'TB_GRUPO_PERMISSAO',
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='permissoes',
            field=models.ManyToManyField(related_name='grupo_set', through='autenticacao.GrupoPermissao', to='autenticacao.permissao'),
        ),
    ]
