# Generated by Django 4.2.23 on 2025-06-12 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_remove_cliente_naturalidade_and_more'),
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalusuario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='historicalusuario',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='historicalusuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='historicalusuario',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='historicalusuario',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='historicalusuario',
            name='nome_social',
        ),
        migrations.RemoveField(
            model_name='historicalusuario',
            name='pais_origem',
        ),
        migrations.RemoveField(
            model_name='historicalusuario',
            name='profissao',
        ),
        migrations.RemoveField(
            model_name='historicalusuario',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='historicalusuario',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='contatos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='enderecos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nome_social',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='pais_origem',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='profissao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefone',
        ),
        migrations.AddField(
            model_name='historicalusuario',
            name='cliente',
            field=models.ForeignKey(blank=True, db_column='FK_CLIENTE', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cliente.cliente'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cliente',
            field=models.ForeignKey(db_column='FK_CLIENTE', null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente'),
        ),
        migrations.AlterField(
            model_name='historicalusuario',
            name='user',
            field=models.ForeignKey(blank=True, db_column='FK_USER', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(db_column='FK_USER', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
