# Generated by Django 4.2.23 on 2025-06-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_remove_historicalusuario_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariobase',
            name='username',
            field=models.CharField(db_column='CO_USUARIO', max_length=35, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
