# Generated by Django 4.2.23 on 2025-06-13 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enderecos', '0004_auto_20250612_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='DT_CRIADO_EM', verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='DT_ATUALIZADO_EM', verbose_name='Atualizado em')),
                ('id', models.AutoField(db_column='PK_LOJA', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NO_LOJA', max_length=120, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, db_column='DS_LOJA', null=True, verbose_name='Descrição')),
                ('status', models.BooleanField(db_column='ST_ATIVO', default=True)),
                ('justificativa', models.TextField(blank=True, db_column='DS_JUSTIFICATIVA', null=True, verbose_name='Justificativa')),
                ('endereco', models.ForeignKey(blank=True, db_column='FK_ENDERECO', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lojas', to='enderecos.endereco', verbose_name='enderecos.Endereco._meta.verbose_name')),
            ],
            options={
                'verbose_name': 'Loja',
                'db_table': 'TB_LOJA',
            },
        ),
        migrations.CreateModel(
            name='HistoricalLoja',
            fields=[
                ('criado_em', models.DateTimeField(blank=True, db_column='DT_CRIADO_EM', editable=False, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(blank=True, db_column='DT_ATUALIZADO_EM', editable=False, verbose_name='Atualizado em')),
                ('id', models.IntegerField(blank=True, db_column='PK_LOJA', db_index=True)),
                ('nome', models.CharField(db_column='NO_LOJA', db_index=True, max_length=120, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, db_column='DS_LOJA', null=True, verbose_name='Descrição')),
                ('status', models.BooleanField(db_column='ST_ATIVO', default=True)),
                ('justificativa', models.TextField(blank=True, db_column='DS_JUSTIFICATIVA', null=True, verbose_name='Justificativa')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('endereco', models.ForeignKey(blank=True, db_column='FK_ENDERECO', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='enderecos.endereco', verbose_name='enderecos.Endereco._meta.verbose_name')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='historico_unidade', to='lojas.loja')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Loja',
                'verbose_name_plural': 'historical Lojas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
