# Generated by Django 4.2.23 on 2025-06-13 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_auto_20250612_1304'),
        ('lojas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LojaContato',
            fields=[
                ('id', models.AutoField(db_column='PK_LOJA_CONTATO', primary_key=True, serialize=False)),
                ('contato', models.ForeignKey(db_column='FK_CONTATO', on_delete=django.db.models.deletion.CASCADE, to='contatos.contato')),
                ('loja', models.ForeignKey(db_column='FK_LOJA', on_delete=django.db.models.deletion.CASCADE, to='lojas.loja')),
            ],
            options={
                'db_table': 'TB_LOJA_CONTATO',
            },
        ),
        migrations.AddField(
            model_name='loja',
            name='contatos',
            field=models.ManyToManyField(related_name='contatos', through='lojas.LojaContato', to='contatos.contato'),
        ),
    ]
