# Generated by Django 4.2.23 on 2025-06-13 02:30

from django.db import migrations

def criar_loja_matriz(apps, schema_editor):
    Loja = apps.get_model('lojas', 'Loja')
    Loja.objects.get_or_create(
        nome='Loja1',
        descricao='Matriz',
        status=True,
        endereco=None,
        justificativa=None
    )
class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0002_lojacontato_loja_contatos'),
    ]

    operations = [
        migrations.RunPython(criar_loja_matriz),
    ]
