# Generated by Django 4.2.23 on 2025-06-13 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='DT_CRIADO_EM', verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='DT_ATUALIZADO_EM', verbose_name='Atualizado em')),
                ('id', models.AutoField(db_column='PK_FABRICANTE', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NO_FABRICANTE', max_length=120, unique=True, verbose_name='Nome')),
                ('nome_reduzido', models.CharField(blank=True, db_column='NO_NOME_REDUZIDO', max_length=20, null=True, verbose_name='Nome Reduzido')),
                ('ativo', models.BooleanField(db_column='ST_ATIVO', default=True)),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
                'db_table': 'TB_FABRICANTE',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='DT_CRIADO_EM', verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='DT_ATUALIZADO_EM', verbose_name='Atualizado em')),
                ('id', models.AutoField(db_column='PK_ITEM', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NO_NOME_ITEM', max_length=120)),
                ('nome_reduzido', models.CharField(blank=True, db_column='NO_NOME_REDUZIDO', max_length=20, null=True, verbose_name='Nome Reduzido')),
                ('descricao', models.TextField(blank=True, db_column='DS_NOME_ITEM', null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(db_column='ST_ATIVO', default=True)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'db_table': 'TB_ITEM',
            },
        ),
        migrations.CreateModel(
            name='HistoricalItem',
            fields=[
                ('criado_em', models.DateTimeField(blank=True, db_column='DT_CRIADO_EM', editable=False, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(blank=True, db_column='DT_ATUALIZADO_EM', editable=False, verbose_name='Atualizado em')),
                ('id', models.IntegerField(blank=True, db_column='PK_ITEM', db_index=True)),
                ('nome', models.CharField(db_column='NO_NOME_ITEM', max_length=120)),
                ('nome_reduzido', models.CharField(blank=True, db_column='NO_NOME_REDUZIDO', max_length=20, null=True, verbose_name='Nome Reduzido')),
                ('descricao', models.TextField(blank=True, db_column='DS_NOME_ITEM', null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(db_column='ST_ATIVO', default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='historico_vacina_catalogo', to='catalogo.item')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Item',
                'verbose_name_plural': 'historical Itens',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFabricante',
            fields=[
                ('criado_em', models.DateTimeField(blank=True, db_column='DT_CRIADO_EM', editable=False, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(blank=True, db_column='DT_ATUALIZADO_EM', editable=False, verbose_name='Atualizado em')),
                ('id', models.IntegerField(blank=True, db_column='PK_FABRICANTE', db_index=True)),
                ('nome', models.CharField(db_column='NO_FABRICANTE', db_index=True, max_length=120, verbose_name='Nome')),
                ('nome_reduzido', models.CharField(blank=True, db_column='NO_NOME_REDUZIDO', max_length=20, null=True, verbose_name='Nome Reduzido')),
                ('ativo', models.BooleanField(db_column='ST_ATIVO', default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='historico_fabricante', to='catalogo.fabricante')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Fabricante',
                'verbose_name_plural': 'historical Fabricantes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ItemFabricante',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='DT_CRIADO_EM', verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='DT_ATUALIZADO_EM', verbose_name='Atualizado em')),
                ('id', models.AutoField(db_column='PK_ITEM_FABRICANTE', primary_key=True, serialize=False)),
                ('fabricante', models.ForeignKey(blank=True, db_column='FK_FABRICANTE', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_fabricante', to='catalogo.fabricante', verbose_name='Fabricante')),
                ('item', models.ForeignKey(blank=True, db_column='FK_ITEM', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_fabricante', to='catalogo.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Relação Item Fabricante',
                'verbose_name_plural': 'Relações Itens Fabricantes',
                'db_table': 'RL_ITEM_FABRICANTE',
                'unique_together': {('item', 'fabricante')},
            },
        ),
    ]
