# Generated by Django 4.2.23 on 2025-06-13 00:13

from django.db import migrations

def inserir_itens_fabricantes(apps, schema_editor):
    Item = apps.get_model('catalogo', 'Item')
    Fabricante = apps.get_model('catalogo', 'Fabricante')
    ItemFabricante = apps.get_model('catalogo', 'ItemFabricante')

    nomes_itens = [
        'Sapatos', 'Tênis', 'Sandálias', 'Tamancos', 'Botas',
        'Chinelos', 'Mocassim', 'Oxford', 'Sapatilhas', 'Crocs'
    ]
    nomes_fabricantes = [
        'Nike', 'Adidas', 'Puma', 'Reebok', 'New Balance',
        'Asics', 'Fila', 'Vans', 'Converse', 'Havaianas'
    ]

    # Cria os itens
    itens = {}
    for nome in nomes_itens:
        item_obj, _ = Item.objects.get_or_create(nome=nome)
        itens[nome] = item_obj

    # Cria os fabricantes
    fabricantes = {}
    for nome in nomes_fabricantes:
        fab_obj, _ = Fabricante.objects.get_or_create(nome=nome)
        fabricantes[nome] = fab_obj

    # Agora cria as relações
    relacoes = [
        ('Tênis', 'Nike'),
        ('Tênis', 'Adidas'),
        ('Tênis', 'Puma'),
        ('Tênis', 'Asics'),
        ('Tênis', 'New Balance'),
        ('Sapatos', 'Vans'),
        ('Sapatos', 'Converse'),
        ('Sandálias', 'Havaianas'),
        ('Chinelos', 'Havaianas'),
        ('Tamancos', 'Fila'),
        ('Botas', 'Reebok'),
        ('Mocassim', 'Converse'),
        ('Oxford', 'Vans'),
        ('Sapatilhas', 'Nike'),
        ('Crocs', 'Puma'),
        ('Crocs', 'Adidas'),
    ]

    for nome_item, nome_fab in relacoes:
        ItemFabricante.objects.get_or_create(
            item=itens[nome_item],
            fabricante=fabricantes[nome_fab]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_historicalitem_history_relation'),
    ]

    operations = [

    ]
