# Generated by Django 4.2.23 on 2025-06-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20250613_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfabricante',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='NU_PRECO'),
        ),
        migrations.AddField(
            model_name='itemfabricante',
            name='tamanho_calçado',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='NU_TAMANHO'),
        ),
    ]
