# Generated by Django 4.2.23 on 2025-06-13 00:53

from django.db import migrations
import random
from decimal import Decimal


def popular_tamanho_preco(apps, schema_editor):
    ItemFabricante = apps.get_model('catalogo', 'ItemFabricante')

    tamanhos_possiveis = ['34', '35', '36', '37', '38', '39', '40', '41', '42', '43']
    precos_possiveis = [Decimal('79.90'), Decimal('89.99'), Decimal('99.90'),
                        Decimal('109.90'), Decimal('119.90'), Decimal('129.90')]

    for item_fab in ItemFabricante.objects.all():
        item_fab.tamanho_calçado = random.choice(tamanhos_possiveis)
        item_fab.preco = random.choice(precos_possiveis)
        item_fab.save()

class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_itemfabricante_preco_itemfabricante_tamanho_calçado'),
    ]

    operations = [
        migrations.RunPython(popular_tamanho_preco),
    ]
