# Generated by Django 4.2.23 on 2025-06-13 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20250613_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemfabricante',
            old_name='tamanho_calçado',
            new_name='tamanho_calcado',
        ),
    ]
