# Generated by Django 4.2.23 on 2025-06-15 22:57

import apps.catalogo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_rename_tamanho_calçado_itemfabricante_tamanho_calcado'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfabricante',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=apps.catalogo.models.imagem_path, verbose_name='IM_ITEM_FABRICANTE'),
        ),
    ]
