# Generated by Django 4.2.23 on 2025-06-14 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vinculos', '0002_alter_historicalvinculo_status_alter_vinculo_status'),
        ('cliente', '0002_remove_cliente_naturalidade_and_more'),
        ('estoques', '0004_auto_20250614_0123'),
        ('lojas', '0003_auto_20250613_0230'),
        ('catalogo', '0006_rename_tamanho_calçado_itemfabricante_tamanho_calcado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='DT_CRIADO_EM', verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='DT_ATUALIZADO_EM', verbose_name='Atualizado em')),
                ('id', models.AutoField(db_column='PK_PAGAMENTO', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='NO_PAGAMENTO', max_length=500, null=True, verbose_name='Pagamento')),
                ('status', models.BooleanField(db_column='ST_STATUS', default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'db_table': 'TB_PAGAMENTO',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='DT_CRIADO_EM', verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='DT_ATUALIZADO_EM', verbose_name='Atualizado em')),
                ('id', models.AutoField(db_column='PK_COMPRA', primary_key=True, serialize=False)),
                ('status_compra_online', models.BooleanField(db_column='ST_COMPRA_ONLINE', default=True, verbose_name='Compra_Online')),
                ('catalogo', models.ForeignKey(db_column='FK_ITEM_FABRICANTE', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.itemfabricante', verbose_name='Item_Fabricante')),
                ('cliente', models.ForeignKey(db_column='FK_CLIENTE', null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente', verbose_name='Cliente')),
                ('estoque', models.ForeignKey(db_column='FK_ESTOQUE', null=True, on_delete=django.db.models.deletion.PROTECT, to='estoques.estoque', verbose_name='Estoque')),
                ('loja', models.ForeignKey(db_column='FK_LOJA', null=True, on_delete=django.db.models.deletion.PROTECT, to='lojas.loja', verbose_name='Loja')),
                ('pagamento', models.ForeignKey(db_column='FK_PAGAMENTO', null=True, on_delete=django.db.models.deletion.PROTECT, to='compras.pagamento', verbose_name='PAGAMENTO')),
                ('vendedor', models.ForeignKey(db_column='FK_VINCULO', null=True, on_delete=django.db.models.deletion.PROTECT, to='vinculos.vinculo', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'db_table': 'TB_COMPRA',
            },
        ),
    ]
