# Generated by Django 4.2.23 on 2025-06-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='qtd_compra',
            field=models.PositiveBigIntegerField(db_column='QT_COMPRA', default=1, verbose_name='Quantidade Compra'),
            preserve_default=False,
        ),
    ]
