# Generated by Django 4.2.23 on 2025-06-14 23:13

from django.db import migrations

def criar_pagamentos(apps, schema_editor):
    Pagamento = apps.get_model('compras', 'Pagamento')
    pagamentos = ['Pix', 'Dinheiro', 'Débito', 'Crédito']

    for nome in pagamentos:
        Pagamento.objects.get_or_create(nome=nome)

class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compra_qtd_compra'),
    ]

    operations = [
        migrations.RunPython(criar_pagamentos),
    ]
