# Generated by Django 4.2.23 on 2025-06-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_auto_20250614_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='cancelar_compra',
            field=models.BooleanField(db_column='ST_CANCELAR_COMPRA', default=False, verbose_name='Cancelar_Compra'),
        ),
        migrations.AddField(
            model_name='compra',
            name='compra_finalizada',
            field=models.BooleanField(db_column='ST_COMPRA_FINALIZADA', default=False, verbose_name='Compra_Finalizada'),
        ),
    ]
