# Generated by Django 4.2.23 on 2025-06-17 01:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_compra_cancelar_compra_compra_compra_finalizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='dt_cancelamento',
            field=models.DateTimeField(auto_now_add=True, db_column='DT_CANCELAMENTO', default=django.utils.timezone.now, verbose_name='Cancelado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='dt_finalizacao',
            field=models.DateTimeField(auto_now_add=True, db_column='DT_FINALIZACAO', default=django.utils.timezone.now, verbose_name='Finalizado em'),
            preserve_default=False,
        ),
    ]
