# Generated by Django 4.2.23 on 2025-06-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_compra_dt_cancelamento_compra_dt_finalizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='dt_cancelamento',
            field=models.DateTimeField(db_column='DT_CANCELAMENTO', verbose_name='Cancelado em'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='dt_finalizacao',
            field=models.DateTimeField(db_column='DT_FINALIZACAO', verbose_name='Finalizado em'),
        ),
    ]
