# Generated by Django 4.2.23 on 2025-06-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_alter_compra_dt_cancelamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='dt_cancelamento',
            field=models.DateTimeField(db_column='DT_CANCELAMENTO', null=True, verbose_name='Cancelado em'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='dt_finalizacao',
            field=models.DateTimeField(db_column='DT_FINALIZACAO', null=True, verbose_name='Finalizado em'),
        ),
    ]
