# Generated by Django 4.2.23 on 2025-06-12 03:13

import apps.cliente.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contatos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='DT_CRIADO_EM', verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='DT_ATUALIZADO_EM', verbose_name='Atualizado em')),
                ('id', models.AutoField(db_column='PK_CLIENTE', primary_key=True, serialize=False)),
                ('cpf', localflavor.br.models.BRCPFField(blank=True, db_column='CO_CPF', db_index=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('nome_completo', models.CharField(db_column='NO_NOME_COMPLETO', db_index=True, max_length=255)),
                ('nome_social', models.CharField(blank=True, db_column='NO_NOME_SOCIAL', max_length=255, null=True, verbose_name='Nome Social')),
                ('nome_mae', models.CharField(blank=True, db_column='NO_NOME_MAE', max_length=255, null=True, verbose_name='Nome da Mãe')),
                ('data_nascimento', models.DateField(db_column='DT_NASCIMENTO', db_index=True, null=True, verbose_name='data de nascimento')),
                ('profissao', models.TextField(db_column='NO_PROFISSAO', verbose_name='Profissão ou trabalho')),
                ('passaporte', models.CharField(blank=True, db_column='NO_PASSAPORTE', max_length=8, null=True)),
                ('foto', models.FileField(blank=True, db_column='NO_FOTO', max_length=200, null=True, upload_to=apps.cliente.models.imagem_perfil_path, validators=[apps.cliente.models.validate_file_extension])),
                ('sexo', models.CharField(choices=[('I', 'Ignorado'), ('M', 'Masculino'), ('F', 'Feminino')], db_column='CO_SEXO', max_length=1, null=True)),
                ('raca', models.CharField(choices=[('01', 'Branca'), ('02', 'Preta'), ('03', 'Parda'), ('04', 'Amarela'), ('05', 'Indígena'), ('99', 'Sem informação')], db_column='CO_RACA', max_length=2, null=True, verbose_name='Raça/Cor')),
                ('contato', models.ForeignKey(blank=True, db_column='FK_CONTATO', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente_contatos', to='contatos.contato', verbose_name='contato')),
            ],
            options={
                'verbose_name': 'Cliente',
                'db_table': 'TB_CLIENTE',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCliente',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(blank=True, db_column='DT_CRIADO_EM', editable=False, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(blank=True, db_column='DT_ATUALIZADO_EM', editable=False, verbose_name='Atualizado em')),
                ('id', models.IntegerField(blank=True, db_column='PK_CLIENTE', db_index=True)),
                ('cpf', localflavor.br.models.BRCPFField(blank=True, db_column='CO_CPF', db_index=True, max_length=14, null=True, verbose_name='CPF')),
                ('nome_completo', models.CharField(db_column='NO_NOME_COMPLETO', db_index=True, max_length=255)),
                ('nome_social', models.CharField(blank=True, db_column='NO_NOME_SOCIAL', max_length=255, null=True, verbose_name='Nome Social')),
                ('nome_mae', models.CharField(blank=True, db_column='NO_NOME_MAE', max_length=255, null=True, verbose_name='Nome da Mãe')),
                ('data_nascimento', models.DateField(db_column='DT_NASCIMENTO', db_index=True, null=True, verbose_name='data de nascimento')),
                ('profissao', models.TextField(db_column='NO_PROFISSAO', verbose_name='Profissão ou trabalho')),
                ('passaporte', models.CharField(blank=True, db_column='NO_PASSAPORTE', max_length=8, null=True)),
                ('foto', models.TextField(blank=True, db_column='NO_FOTO', max_length=200, null=True, validators=[apps.cliente.models.validate_file_extension])),
                ('sexo', models.CharField(choices=[('I', 'Ignorado'), ('M', 'Masculino'), ('F', 'Feminino')], db_column='CO_SEXO', max_length=1, null=True)),
                ('raca', models.CharField(choices=[('01', 'Branca'), ('02', 'Preta'), ('03', 'Parda'), ('04', 'Amarela'), ('05', 'Indígena'), ('99', 'Sem informação')], db_column='CO_RACA', max_length=2, null=True, verbose_name='Raça/Cor')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contato', models.ForeignKey(blank=True, db_column='FK_CONTATO', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contatos.contato', verbose_name='contato')),
                ('endereco', models.ForeignKey(blank=True, db_column='FK_ENDERECO', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='enderecos.endereco', verbose_name='endereço')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='historico_cliente', to='cliente.cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('naturalidade', models.ForeignKey(blank=True, db_column='FK_MUNICIPIO_NATURALIDADE', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='enderecos.municipio', verbose_name='Naturalidade')),
                ('pais_origem', models.ForeignKey(blank=True, db_column='FK_PAIS_ORIGEM', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='enderecos.pais', verbose_name='País de origem')),
                ('user', models.ForeignKey(blank=True, db_column='FK_USUARIO_BASE', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'historical Cliente',
                'verbose_name_plural': 'historical Clientes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ClienteEndereco',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='DT_CRIADO_EM', verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='DT_ATUALIZADO_EM', verbose_name='Atualizado em')),
                ('id', models.AutoField(db_column='PK_CLIENTE_ENDERECO', primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(db_column='FK_CLIENTE', on_delete=django.db.models.deletion.PROTECT, related_name='clientes_endereco', to='cliente.cliente')),
                ('endereco', models.ForeignKey(db_column='FK_ENDERECO', on_delete=django.db.models.deletion.PROTECT, related_name='enderecos_cliente', to='enderecos.endereco')),
            ],
            options={
                'verbose_name': 'Endereço do cliente',
                'db_table': 'RL_CLIENTE_ENDERECO',
            },
        ),
        migrations.CreateModel(
            name='ClienteContato',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='DT_CRIADO_EM', verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='DT_ATUALIZADO_EM', verbose_name='Atualizado em')),
                ('id', models.AutoField(db_column='PK_CLIENTE_CONTATO', primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(db_column='FK_CLIENTE', on_delete=django.db.models.deletion.CASCADE, related_name='cliente_contatos', to='cliente.cliente')),
                ('contato', models.ForeignKey(db_column='FK_CONTATO', on_delete=django.db.models.deletion.CASCADE, related_name='contatos_cliente', to='contatos.contato')),
            ],
            options={
                'verbose_name': 'Contato do cliente',
                'db_table': 'RL_CLIENTE_CONTATO',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='contatos',
            field=models.ManyToManyField(through='cliente.ClienteContato', to='contatos.contato'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(db_column='FK_ENDERECO', on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='enderecos.endereco', verbose_name='endereço'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='enderecos',
            field=models.ManyToManyField(through='cliente.ClienteEndereco', to='enderecos.endereco'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='naturalidade',
            field=models.ForeignKey(blank=True, db_column='FK_MUNICIPIO_NATURALIDADE', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='enderecos.municipio', verbose_name='Naturalidade'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais_origem',
            field=models.ForeignKey(blank=True, db_column='FK_PAIS_ORIGEM', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='enderecos.pais', verbose_name='País de origem'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(db_column='FK_USUARIO_BASE', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.CreateModel(
            name='AnexoCliente',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='DT_CRIADO_EM', verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='DT_ATUALIZADO_EM', verbose_name='Atualizado em')),
                ('id', models.AutoField(db_column='PK_ANEXO_CLIENTE', primary_key=True, serialize=False)),
                ('arquivo', models.FileField(db_column='NO_ARQUIVO', max_length=255, upload_to=apps.cliente.models.anexo_cliente_path)),
                ('cliente', models.ForeignKey(db_column='FK_CLIENTE', on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente', verbose_name='Cliente')),
            ],
            options={
                'db_table': 'TB_ANEXO_CLIENTE',
            },
        ),
        migrations.AddConstraint(
            model_name='clienteendereco',
            constraint=models.UniqueConstraint(fields=('cliente', 'endereco'), name='uk_cliente_endereco'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(check=models.Q(('cpf__isnull', False), ('passaporte__isnull', False), _connector='OR'), name='not_both_null'),
        ),
    ]
