# Generated by Django 4.2.23 on 2025-06-12 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='naturalidade',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='pais_origem',
        ),
        migrations.RemoveField(
            model_name='historicalcliente',
            name='naturalidade',
        ),
        migrations.RemoveField(
            model_name='historicalcliente',
            name='pais_origem',
        ),
    ]
