# Generated by Django 4.2.23 on 2025-06-15 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0004_auto_20250612_1309'),
        ('cliente', '0002_remove_cliente_naturalidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(db_column='FK_ENDERECO', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='enderecos.endereco', verbose_name='endereço'),
        ),
    ]
