# Generated by Django 4.2.23 on 2025-06-15 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_cliente_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cliente',
            name='not_both_null',
        ),
    ]
