# Generated by Django 4.2.23 on 2025-06-13 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacao', '0002_remove_historicalusuario_cpf_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lojas', '0002_lojacontato_loja_contatos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='DT_CRIADO_EM', verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='DT_ATUALIZADO_EM', verbose_name='Atualizado em')),
                ('id', models.AutoField(db_column='PK_VINCULO', primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'Aguardando Homologação'), (1, 'Vínculo Autorizado'), (2, 'Vínculo Inativo')], db_column='ST_VINCULO', db_index=True, default=0)),
                ('perfil', models.IntegerField(choices=[(0, 'Administrador'), (1, 'Vendedor')], db_column='ST_PERFIL', db_index=True, default=0)),
                ('data_autorizacao', models.DateTimeField(db_column='DT_AUTORIZACAO', null=True)),
                ('data_inativacao', models.DateTimeField(db_column='DT_INATIVACAO', null=True)),
                ('autorizado_por_usuario', models.ForeignKey(db_column='AUTORIZADOR_POR', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_autorizados', to='autenticacao.usuario')),
                ('inativado_por_usuario', models.ForeignKey(db_column='INATIVADO_POR', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_inativados', to='autenticacao.usuario')),
                ('loja', models.ForeignKey(db_column='FK_UNIDADE_CADEIA_FRIO', on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='lojas.loja')),
                ('usuario', models.ForeignKey(db_column='FK_USUARIO', on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='autenticacao.usuario')),
            ],
            options={
                'verbose_name': 'Vínculo',
                'verbose_name_plural': 'Vínculos',
                'db_table': 'TB_USUARIO_VINCULO',
            },
        ),
        migrations.CreateModel(
            name='HistoricalVinculo',
            fields=[
                ('criado_em', models.DateTimeField(blank=True, db_column='DT_CRIADO_EM', editable=False, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(blank=True, db_column='DT_ATUALIZADO_EM', editable=False, verbose_name='Atualizado em')),
                ('id', models.IntegerField(blank=True, db_column='PK_VINCULO', db_index=True)),
                ('status', models.IntegerField(choices=[(0, 'Aguardando Homologação'), (1, 'Vínculo Autorizado'), (2, 'Vínculo Inativo')], db_column='ST_VINCULO', db_index=True, default=0)),
                ('perfil', models.IntegerField(choices=[(0, 'Administrador'), (1, 'Vendedor')], db_column='ST_PERFIL', db_index=True, default=0)),
                ('data_autorizacao', models.DateTimeField(db_column='DT_AUTORIZACAO', null=True)),
                ('data_inativacao', models.DateTimeField(db_column='DT_INATIVACAO', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('autorizado_por_usuario', models.ForeignKey(blank=True, db_column='AUTORIZADOR_POR', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='autenticacao.usuario')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='historico_vinculo', to='vinculos.vinculo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inativado_por_usuario', models.ForeignKey(blank=True, db_column='INATIVADO_POR', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='autenticacao.usuario')),
                ('loja', models.ForeignKey(blank=True, db_column='FK_UNIDADE_CADEIA_FRIO', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lojas.loja')),
                ('usuario', models.ForeignKey(blank=True, db_column='FK_USUARIO', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='autenticacao.usuario')),
            ],
            options={
                'verbose_name': 'historical Vínculo',
                'verbose_name_plural': 'historical Vínculos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
