# Generated by Django 4.2.23 on 2025-06-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvinculo',
            name='status',
            field=models.IntegerField(choices=[(0, 'Vínculo Ativo'), (1, 'Vínculo Inativo')], db_column='ST_VINCULO', db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='vinculo',
            name='status',
            field=models.IntegerField(choices=[(0, 'Vínculo Ativo'), (1, 'Vínculo Inativo')], db_column='ST_VINCULO', db_index=True, default=0),
        ),
    ]
