# Generated by Django 4.2.23 on 2025-06-15 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0003_auto_20250613_0230'),
        ('autenticacao', '0002_remove_historicalusuario_cpf_and_more'),
        ('vinculos', '0002_alter_historicalvinculo_status_alter_vinculo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvinculo',
            name='perfil',
            field=models.IntegerField(choices=[(0, 'Administrador'), (1, 'Vendedor')], db_column='ST_PERFIL', db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vinculo',
            name='loja',
            field=models.ForeignKey(db_column='FK_UNIDADE_CADEIA_FRIO', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='lojas.loja'),
        ),
        migrations.AlterField(
            model_name='vinculo',
            name='perfil',
            field=models.IntegerField(choices=[(0, 'Administrador'), (1, 'Vendedor')], db_column='ST_PERFIL', db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vinculo',
            name='usuario',
            field=models.ForeignKey(db_column='FK_USUARIO', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='autenticacao.usuario'),
        ),
    ]
