# Generated by Django 4.2.23 on 2025-06-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculos', '0003_alter_historicalvinculo_perfil_alter_vinculo_loja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvinculo',
            name='perfil',
            field=models.IntegerField(choices=[(0, 'Administrador'), (1, 'Vendedor')], db_column='ST_PERFIL', db_index=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='vinculo',
            name='perfil',
            field=models.IntegerField(choices=[(0, 'Administrador'), (1, 'Vendedor')], db_column='ST_PERFIL', db_index=True, default=1, null=True),
        ),
    ]
