# Generated by Django 4.2.23 on 2025-06-16 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0003_auto_20250613_0230'),
        ('vinculos', '0004_alter_historicalvinculo_perfil_alter_vinculo_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvinculo',
            name='loja',
            field=models.ForeignKey(blank=True, db_column='FK_LOJA', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lojas.loja'),
        ),
        migrations.AlterField(
            model_name='vinculo',
            name='loja',
            field=models.ForeignKey(db_column='FK_LOJA', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='lojas.loja'),
        ),
    ]
