# Generated by Django 4.2.23 on 2025-06-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculos', '0005_alter_historicalvinculo_loja_alter_vinculo_loja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvinculo',
            name='perfil',
            field=models.IntegerField(choices=[(0, 'Administrador'), (1, 'Vendedor'), (2, 'Gerente')], db_column='ST_PERFIL', db_index=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='vinculo',
            name='perfil',
            field=models.IntegerField(choices=[(0, 'Administrador'), (1, 'Vendedor'), (2, 'Gerente')], db_column='ST_PERFIL', db_index=True, default=1, null=True),
        ),
    ]
