# Generated by Django 4.2.23 on 2025-06-12 13:04

from django.db import migrations


def adicionar_tipos_contato(apps, schema_editor):
    TipoContato = apps.get_model('contatos', 'TipoContato')

    TipoContato.objects.update_or_create(
        nome='Telefone',
        defaults={
            'expressao_validacao': r'^\(?\d{2}\)?[\s-]?\d{4,5}-?\d{4}$',
            'formato': '(XX) XXXXX-XXXX'
        }
    )

    TipoContato.objects.update_or_create(
        nome='E-mail',
        defaults={
            'expressao_validacao': r'^[\w\.-]+@[\w\.-]+\.\w+$',
            'formato': 'exemplo@dominio.com'
        }
    )
class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(adicionar_tipos_contato),
    ]
