# Generated by Django 4.2.23 on 2025-06-13 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0006_rename_tamanho_calçado_itemfabricante_tamanho_calcado'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='DT_CRIADO_EM', verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='DT_ATUALIZADO_EM', verbose_name='Atualizado em')),
                ('id', models.AutoField(db_column='PK_ESTOQUE', primary_key=True, serialize=False)),
                ('perda_tecnica', models.PositiveBigIntegerField(db_column='QT_PERDA_TECNICA', default=0, verbose_name='Perda técnica')),
                ('qtd_estoque', models.PositiveBigIntegerField(db_column='QT_ESTOQUE', default=0, verbose_name='Quantidade liberada do itens')),
                ('qtd_bloqueada', models.PositiveBigIntegerField(db_column='QT_BLOQUEADA', default=0, verbose_name='Quantidade bloqueada de itens')),
                ('qtd_reservada', models.PositiveBigIntegerField(db_column='QT_RESERVADA', default=0, verbose_name='Quantidade reservada de itens')),
                ('descricao', models.CharField(blank=True, db_column='NO_DESCRICAO', max_length=500, null=True, verbose_name='Descrição')),
                ('catalogo', models.ForeignKey(db_column='FK_ITEM_FABRICANTE', default=1, on_delete=django.db.models.deletion.PROTECT, to='catalogo.itemfabricante', verbose_name='Item_Fabricante')),
            ],
            options={
                'verbose_name': 'Estoque',
                'db_table': 'TB_ESTOQUE',
            },
        ),
        migrations.CreateModel(
            name='TipoTransacaoEstoque',
            fields=[
                ('id', models.IntegerField(choices=[(1, 'Compra'), (2, 'Cancelamento Compra'), (3, 'Venda'), (4, 'Cancelamento Venda'), (5, 'Perca Tecnica'), (6, 'Devolucao')], db_column='PK_TIPO_TRANSACAO', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME', max_length=100, unique=True)),
                ('sigla', models.CharField(db_column='SIGLA', max_length=5, unique=True)),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], db_column='TIPO', max_length=1)),
            ],
            options={
                'db_table': 'TB_TIPO_TRANSACAO_ESTOQUE',
            },
        ),
        migrations.CreateModel(
            name='TransacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_transacao', models.IntegerField(db_column='CHAVE_TRANSACAO')),
                ('quantidade', models.IntegerField(db_column='QUANTIDADE')),
                ('realizada_em', models.DateTimeField(db_column='DT_REALIZADA_EM')),
                ('registrada_em', models.DateTimeField(auto_now_add=True, db_column='DT_CADASTRADO_EM')),
                ('observacao', models.CharField(blank=True, db_column='DS_OBSERVACAO', max_length=255, null=True, verbose_name='Observação')),
                ('cancelada_por', models.ForeignKey(blank=True, db_column='FK_TRANSACAO_REVERSAO', null=True, on_delete=django.db.models.deletion.PROTECT, to='estoques.transacaoestoque')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('estoque', models.ForeignKey(db_column='FK_ESTOQUE', on_delete=django.db.models.deletion.PROTECT, to='estoques.estoque')),
                ('tipo', models.ForeignKey(db_column='PK_TIPO_TRANSACAO', on_delete=django.db.models.deletion.PROTECT, to='estoques.tipotransacaoestoque')),
            ],
            options={
                'verbose_name': 'Transação do estoque',
                'verbose_name_plural': 'Transações dos estoques',
                'db_table': 'TB_TRANSACAO_ESTOQUE',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEstoque',
            fields=[
                ('criado_em', models.DateTimeField(blank=True, db_column='DT_CRIADO_EM', editable=False, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(blank=True, db_column='DT_ATUALIZADO_EM', editable=False, verbose_name='Atualizado em')),
                ('id', models.IntegerField(blank=True, db_column='PK_ESTOQUE', db_index=True)),
                ('perda_tecnica', models.PositiveBigIntegerField(db_column='QT_PERDA_TECNICA', default=0, verbose_name='Perda técnica')),
                ('qtd_estoque', models.PositiveBigIntegerField(db_column='QT_ESTOQUE', default=0, verbose_name='Quantidade liberada do itens')),
                ('qtd_bloqueada', models.PositiveBigIntegerField(db_column='QT_BLOQUEADA', default=0, verbose_name='Quantidade bloqueada de itens')),
                ('qtd_reservada', models.PositiveBigIntegerField(db_column='QT_RESERVADA', default=0, verbose_name='Quantidade reservada de itens')),
                ('descricao', models.CharField(blank=True, db_column='NO_DESCRICAO', max_length=500, null=True, verbose_name='Descrição')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('catalogo', models.ForeignKey(blank=True, db_column='FK_ITEM_FABRICANTE', db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.itemfabricante', verbose_name='Item_Fabricante')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='historico_estoque', to='estoques.estoque')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Estoque',
                'verbose_name_plural': 'historical Estoques',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
