# Generated by Django 4.2.23 on 2025-06-13 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinculos', '0001_initial'),
        ('lojas', '0002_lojacontato_loja_contatos'),
        ('estoques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='loja',
            field=models.ForeignKey(db_column='FK_LOJA', null=True, on_delete=django.db.models.deletion.PROTECT, to='lojas.loja', verbose_name='Loja'),
        ),
        migrations.AddField(
            model_name='historicalestoque',
            name='loja',
            field=models.ForeignKey(blank=True, db_column='FK_LOJA', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lojas.loja', verbose_name='Loja'),
        ),
        migrations.AddField(
            model_name='transacaoestoque',
            name='usuario_cadastro',
            field=models.ForeignKey(db_column='FK_USUARIO_CADASTRO', null=True, on_delete=django.db.models.deletion.PROTECT, to='vinculos.vinculo', verbose_name='Usuário que cadastrou a transação do estoque'),
        ),
    ]
