# Generated by Django 4.2.23 on 2025-06-14 01:23

from django.db import migrations

def criar_estoque_inicial(apps, schema_editor):
    Estoque = apps.get_model('estoques', 'Estoque')
    ItemFabricante = apps.get_model('catalogo', 'ItemFabricante')
    Loja = apps.get_model('lojas', 'Loja')

    try:
        loja = Loja.objects.first()  # ou filtre pela loja correta se necessário
    except Loja.DoesNotExist:
        return


    estoques = [
        1, 2, 3, 4, 5, 6, 7, 8,
        10, 11, 12, 13, 14, 15, 16, 17, 9
    ]

    for item_id in estoques:
        try:
            item = ItemFabricante.objects.get(id=item_id)
            Estoque.objects.get_or_create(
                catalogo=item,
                loja=loja,
                qtd_estoque=50,
                descricao="Estoque inicial adicionado via migração"
            )
        except ItemFabricante.DoesNotExist:
            continue
class Migration(migrations.Migration):

    dependencies = [
        ('estoques', '0003_remove_estoque_perda_tecnica_and_more'),
    ]

    operations = [
        migrations.RunPython(criar_estoque_inicial),
    ]
