# Generated by Django 4.2.23 on 2025-06-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoques', '0004_auto_20250614_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='qtd_reservada',
            field=models.PositiveBigIntegerField(db_column='QT_RESERVADA', default=0, verbose_name='Quantidade reservada'),
        ),
        migrations.AddField(
            model_name='historicalestoque',
            name='qtd_reservada',
            field=models.PositiveBigIntegerField(db_column='QT_RESERVADA', default=0, verbose_name='Quantidade reservada'),
        ),
    ]
